name: 🔂 Surge PR Preview

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]
  push:

jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: afc163/surge-preview@v1
        with:
          surge_token: ${{ secrets.SURGE_TOKEN }}
          github_token: ${{ secrets.TOKEN }}
          dist: public
          teardown: "true"
          build: |
            npm install
            npm run build
